-- Daily net totals from Tradovate Performance CSV (public.performance_daily).
-- Matches Supabase table: BIGINT id, DATE day, UNIQUE(account, day).

CREATE TABLE IF NOT EXISTS public.performance_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account TEXT NOT NULL,
    day DATE NOT NULL,
    net_total NUMERIC NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (account, day)
);

ALTER TABLE public.performance_daily ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access" ON public.performance_daily FOR ALL USING (true);
